### ISSUE TITLE
DAOs

### ISSUE THREAD

**Issue by Jeisson005** [JustawayL/RRotonda#2]
Se deben reestructurar los métodos de los DAOs para:

1. Adaptarse a la nueva lógica de negocio que se propuso (Ver el modelo en StarUML)
2. Se deben utilizar los constructores provistos por el modelo
3. En los casos que se requieren llaves foraneas (Por ejemplo el pedido que tiene un cliente como atributo) es necesario que se construya un cliente utilizando el constructor que únicamente requiere ID
Tener en cuenta también el modelo de BD (Sin restaurante) también en StarUML

**Comment by Jeisson005** [comment]
El punto número 2 quedó solucionado, puesto que corregí la manera en como se usa el constructor
Es valido llamar constructores sin ningún parámetro ahora
Queda verificar los otros dos puntos

**Comment by JustawayL** [comment]
@Jeisson005 En el caso de las llaves foráneas es mejor retornar solo el valor del ID en vez de un objeto con un solo atributo.

**Comment by Jeisson005** [comment]
Por qué? @JustawayL 
Cuando yo requiera más datos de dicha llave que en realidad es un objeto y para mantener la composición es mejor tener siempre un objeto

**Comment by JustawayL** [comment]
@Jeisson005 Para las consultas los Dao tienen como parámetros llaves mas no objetos, es decir nadie esta agregando mas atributos a ese objeto si se llega a crear.

**Comment by Jeisson005** [comment]
@JustawayL Yo sí podría llegar a agregar más atributos en el momento de usar los objetos resultantes
